[package]
name = "kvad-tui"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Terminal UI for browsing, downloading and chatting with local models."

[[bin]]
name = "kvad-tui"
path = "src/main.rs"

[dependencies]
kvad = { path = "../llm" }
kvad-gpu = { version = "0.1.0", path = "../gpu" }
ratatui = "0.29.0"
