//! HTML in, Markdown-ish text out.
//!
//! Not a browser and not a spec-compliant parser: a scanner that knows which
//! elements carry prose, which carry furniture, and which carry code. That is
//! enough for the thing anybody actually points a crawler at — a documentation
//! site, whose HTML is generated by one program from one template — and it
//! costs no dependency and no tree.
//!
//! # What it is allowed to get wrong
//!
//! Hostile or broken markup turns into noisy text, never into a panic and
//! never into a hang: every scan moves forward, and an unterminated tag ends
//! at the end of the document. A page that comes out badly is a page with a
//! bad ratio of prose to junk, which the character histogram at the end of a
//! crawl tends to show.
//!
//! # Furniture and its links
//!
//! Dropping `<nav>` and `<script>` is the easy half. The rest of a docs page —
//! the sidebar, the theme picker, the "edit this page" link — is `<div>`s
//! telling you what they are in their `id` and `class`, and [`furniture`]
//! reads that. It is a heuristic, and it is the difference between a corpus
//! that is the Rust book and a corpus that is the Rust book with its table of
//! contents repeated four hundred times.
//!
//! Links are the exception: they are collected from the *whole* document,
//! furniture included. A book's table of contents is in its sidebar, and a
//! crawler that dropped the sidebar before looking for links would fetch one
//! page and stop.

use std::borrow::Cow;

/// What one page turned out to be.
pub struct Page {
    pub title: String,
    pub text: String,
    /// Every `href` as it was written, unresolved: turning `../ch01.html`
    /// into an address needs the page's own, which is the crawler's to know.
    pub links: Vec<String>,
    /// A `<base href>`, if the document had one. Rare, and changes what every
    /// relative link on the page means, so it cannot be ignored.
    pub base: Option<String>,
}

/// Elements whose contents are not prose, dropped whole.
const SKIP: &[&str] = &[
    "script", "style", "noscript", "template", "svg", "canvas", "iframe", "object", "form",
    "select", "button", "nav", "header", "footer", "aside", "dialog", "audio", "video",
];

/// Elements that end the line they are on, and with it any marker waiting
/// for text that never came.
const BLOCKS: &[&str] = &[
    "p", "div", "section", "blockquote", "dd", "dt", "figcaption", "summary", "details", "table",
    "caption", "fieldset", "address", "h1", "h2", "h3", "h4", "h5", "h6", "tr", "ul", "ol", "dl",
    "li", "pre",
];

/// Elements that never close, so skipping one by counting its closes would
/// swallow the rest of the document.
const VOID: &[&str] = &[
    "area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "source",
    "track", "wbr",
];

/// `id`, `class` and `role` tokens that mean "this is not the page".
///
/// `header` is deliberately not here, though the element `<header>` is in
/// [`SKIP`]: `class="header"` is what mdBook and rustdoc put on the anchor
/// inside every heading, and treating that as furniture silently deletes
/// every heading on every page of the two sites this was written for.
const FURNITURE: &[&str] = &[
    "sidebar", "sidetoc", "toc", "menu", "menubar", "nav", "navbar", "navigation", "breadcrumb",
    "breadcrumbs", "footer", "banner", "cookie", "search", "searchbox", "toolbar", "skip",
    "theme", "pagination", "pager", "announcement", "ads", "advertisement", "social", "share",
    "comments",
];

pub fn extract(html: &str) -> Page {
    let title = element(html, "title").map(|t| collapse(&decode(t))).unwrap_or_default();
    let mut build = Build::new();
    build.walk(narrow(html));
    let text = build.finish();
    let (links, base) = refs(html);
    Page { title, text, links, base }
}

/// Every `href` in the document, in the order they appear and without
/// repeats, and the `<base href>` if there is one.
///
/// Over the whole document rather than the narrowed, furniture-free part:
/// see the note at the top. `<head>` is in here too, which is where a `base`
/// lives and where [`narrow`] never looks.
fn refs(html: &str) -> (Vec<String>, Option<String>) {
    let mut links: Vec<String> = Vec::new();
    let mut base = None;
    for node in Scan::new(html) {
        let Node::Open { name, attrs } = node else { continue };
        match name.as_str() {
            "base" => base = base.or_else(|| attr(attrs, "href").map(|h| decode(h).into_owned())),
            "a" => {
                let Some(href) = attr(attrs, "href") else { continue };
                let href = decode(href).trim().to_string();
                let ignorable = href.is_empty()
                    || href.starts_with('#')
                    || ["javascript:", "mailto:", "tel:", "data:"]
                        .iter()
                        .any(|s| href.to_ascii_lowercase().starts_with(s));
                if !ignorable && !links.contains(&href) {
                    links.push(href);
                }
            }
            _ => {}
        }
    }
    (links, base)
}

/// The part of the document that is the document.
///
/// `<main>` first because a page that has one has said where its content is;
/// `<article>` next for the sites that say it the other way; `<body>` as the
/// floor, so that the furniture rules are all that is left to do the work.
fn narrow(html: &str) -> &str {
    ["main", "article", "body"].iter().find_map(|n| element(html, n)).unwrap_or(html)
}

// ---------------------------------------------------------------------------
// The scanner
// ---------------------------------------------------------------------------

enum Node<'a> {
    Text(&'a str),
    Open { name: String, attrs: &'a str },
    Close { name: String },
}

struct Scan<'a> {
    html: &'a str,
    at: usize,
    /// Where the node just returned began. `element` needs it to slice out
    /// the contents of an element without its closing tag.
    last: usize,
}

impl<'a> Scan<'a> {
    fn new(html: &'a str) -> Self {
        Scan { html, at: 0, last: 0 }
    }
}

impl<'a> Iterator for Scan<'a> {
    type Item = Node<'a>;

    fn next(&mut self) -> Option<Node<'a>> {
        // A loop rather than recursion: a document that is a million comments
        // would otherwise be a stack overflow.
        loop {
            self.last = self.at;
            let rest = self.html.get(self.at..)?;
            if rest.is_empty() {
                return None;
            }
            if !rest.starts_with('<') {
                let end = rest.find('<').unwrap_or(rest.len());
                self.at += end;
                return Some(Node::Text(&rest[..end]));
            }
            if rest.starts_with("<!--") {
                self.at += rest.find("-->").map_or(rest.len(), |i| i + 3);
                continue;
            }
            if rest.starts_with("<!") || rest.starts_with("<?") {
                self.at += rest.find('>').map_or(rest.len(), |i| i + 1);
                continue;
            }

            let close = rest.starts_with("</");
            let from = if close { 2 } else { 1 };
            let name_len = rest[from..]
                .find(|c: char| !c.is_ascii_alphanumeric() && c != '-')
                .unwrap_or(rest.len() - from);
            if name_len == 0 {
                // A `<` that begins nothing — arithmetic, usually. It is text.
                self.at += 1;
                return Some(Node::Text(&rest[..1]));
            }
            let name = rest[from..from + name_len].to_ascii_lowercase();
            let end = tag_end(rest);
            let attrs = rest[from + name_len..end].trim_end_matches(['>', '/']);
            self.at += end;

            // Raw-text elements: their contents are not markup, and `a < b` in
            // a script would otherwise become a tag. Jump to the close tag and
            // let the next turn of the loop read it.
            if !close && matches!(name.as_str(), "script" | "style" | "textarea" | "title") {
                let after = &self.html[self.at..];
                self.at += find_ci(after, &format!("</{name}")).unwrap_or(after.len());
            }

            return Some(match close {
                true => Node::Close { name },
                false => Node::Open { name, attrs },
            });
        }
    }
}

/// One past the `>` that ends the tag starting at the front of `rest`.
///
/// Quote-aware, because `<a title="a > b">` is legal and a naive search for
/// `>` would cut the tag in half.
fn tag_end(rest: &str) -> usize {
    let mut quote = None;
    for (i, c) in rest.char_indices() {
        match (quote, c) {
            (Some(q), c) if c == q => quote = None,
            (Some(_), _) => {}
            (None, '"') | (None, '\'') => quote = Some(c),
            (None, '>') => return i + 1,
            (None, _) => {}
        }
    }
    rest.len()
}

/// The contents of the first `<name>` element, without its tags.
fn element<'a>(html: &'a str, name: &str) -> Option<&'a str> {
    let open = find_open(html, name)?;
    let start = open + tag_end(&html[open..]);
    let mut depth = 1usize;
    let mut scan = Scan { html, at: start, last: start };
    while let Some(node) = scan.next() {
        match node {
            Node::Open { name: n, .. } if n == name => depth += 1,
            Node::Close { name: n } if n == name => {
                depth -= 1;
                if depth == 0 {
                    return Some(&html[start..scan.last]);
                }
            }
            _ => {}
        }
    }
    // Never closed. The rest of the document is as good an answer as there is.
    Some(&html[start..])
}

/// Where `<name` opens, as a tag rather than as a prefix of a longer name.
fn find_open(html: &str, name: &str) -> Option<usize> {
    let needle = format!("<{name}");
    let mut from = 0;
    while let Some(i) = find_ci(&html[from..], &needle) {
        let at = from + i;
        let after = html[at + needle.len()..].chars().next();
        match after {
            Some(c) if c.is_ascii_alphanumeric() || c == '-' => from = at + needle.len(),
            _ => return Some(at),
        }
    }
    None
}

/// `str::find`, ignoring ASCII case. `needle` must be lowercase.
fn find_ci(haystack: &str, needle: &str) -> Option<usize> {
    let (h, n) = (haystack.as_bytes(), needle.as_bytes());
    if n.is_empty() || h.len() < n.len() {
        return None;
    }
    (0..=h.len() - n.len()).find(|&i| h[i..i + n.len()].eq_ignore_ascii_case(n))
}

/// The value of one attribute, undecoded.
fn attr<'a>(attrs: &'a str, name: &str) -> Option<&'a str> {
    let mut from = 0;
    while let Some(i) = find_ci(&attrs[from..], name) {
        let at = from + i;
        let before = attrs[..at].chars().next_back();
        let rest = &attrs[at + name.len()..];
        let boundary = before.is_none_or(|c| c.is_whitespace());
        let assigned = rest.trim_start().starts_with('=');
        if boundary && assigned {
            let value = rest.trim_start()[1..].trim_start();
            return Some(match value.chars().next() {
                Some(q @ ('"' | '\'')) => value[1..].split(q).next().unwrap_or(""),
                _ => value.split_whitespace().next().unwrap_or(""),
            });
        }
        from = at + name.len();
    }
    None
}

/// Whether an element's `id`, `class` or `role` says it is not the page.
///
/// Token-wise rather than by substring: `class="sidebar-resize-handle"` is
/// furniture and `class="research-notes"` is not, and a plain `contains` would
/// call both of them a search box.
fn furniture(attrs: &str) -> bool {
    ["id", "class", "role"].iter().filter_map(|a| attr(attrs, a)).any(|value| {
        value.split_whitespace().any(|token| {
            let token = token.to_ascii_lowercase();
            FURNITURE.iter().any(|f| {
                token == *f
                    || token.starts_with(&format!("{f}-"))
                    || token.ends_with(&format!("-{f}"))
            })
        })
    })
}

/// The language of a code block, from `class="language-rust"`.
fn language(attrs: &str) -> String {
    let Some(class) = attr(attrs, "class") else { return String::new() };
    class
        .split_whitespace()
        .find_map(|t| t.strip_prefix("language-").or_else(|| t.strip_prefix("lang-")))
        // `rust,ignore` and `rust,no_run` are mdBook's, and the part after the
        // comma is an instruction to its test runner, not a language.
        .map(|l| l.split(',').next().unwrap_or(l).to_string())
        .unwrap_or_default()
}

// ---------------------------------------------------------------------------
// The document being built
// ---------------------------------------------------------------------------

struct Build {
    out: String,
    /// Newlines owed before the next text. Deferred rather than pushed, so
    /// that three empty `<div>`s in a row cost nothing.
    pending: usize,
    /// A marker — `## `, `- ` — to write after those newlines, if any text
    /// turns up to justify it.
    prefix: Option<String>,
    /// Depth of `<pre>`. Inside one, whitespace is the content.
    pre: usize,
    /// Where a fence's language would go, while it can still be learned from
    /// the `<code>` that follows the `<pre>`.
    fence: Option<usize>,
    /// One entry per open list; `Some(n)` counts an ordered one.
    lists: Vec<Option<usize>>,
    /// The element being dropped whole, and how deep into it we are.
    skip: Option<(String, usize)>,
}

impl Build {
    fn new() -> Self {
        Build {
            out: String::new(),
            pending: 0,
            prefix: None,
            pre: 0,
            fence: None,
            lists: Vec::new(),
            skip: None,
        }
    }

    fn walk(&mut self, html: &str) {
        let mut scan = Scan::new(html);
        while let Some(node) = scan.next() {
            match node {
                Node::Text(t) if self.skip.is_none() => self.text(t),
                Node::Text(_) => {}
                Node::Open { name, attrs } => {
                    if let Some((open, depth)) = &mut self.skip {
                        // A nested one of the same name: it has to close twice.
                        if *open == name && !VOID.contains(&name.as_str()) {
                            *depth += 1;
                        }
                        continue;
                    }
                    if SKIP.contains(&name.as_str()) || furniture(attrs) {
                        if !VOID.contains(&name.as_str()) {
                            self.skip = Some((name, 1));
                        }
                        continue;
                    }
                    self.open(&name, attrs);
                }
                Node::Close { name } => {
                    if let Some((open, depth)) = &mut self.skip {
                        if *open == name {
                            *depth -= 1;
                            if *depth == 0 {
                                self.skip = None;
                            }
                        }
                        continue;
                    }
                    self.close(&name);
                }
            }
        }
    }

    fn open(&mut self, name: &str, attrs: &str) {
        match name {
            "br" => self.block(1),
            "hr" => self.block(2),
            "p" | "div" | "section" | "blockquote" | "dd" | "dt" | "figcaption" | "summary"
            | "details" | "table" | "caption" | "fieldset" | "address" => self.block(2),
            "h1" | "h2" | "h3" | "h4" | "h5" | "h6" => {
                self.block(2);
                let level: usize = name[1..].parse().unwrap_or(1);
                self.prefix = Some(format!("{} ", "#".repeat(level)));
            }
            "ul" | "ol" | "dl" => {
                self.lists.push(matches!(name, "ol").then_some(0));
                self.block(2);
            }
            "li" => {
                self.block(1);
                let indent = "  ".repeat(self.lists.len().saturating_sub(1));
                let marker = match self.lists.last_mut() {
                    Some(Some(n)) => {
                        *n += 1;
                        format!("{n}. ")
                    }
                    _ => "- ".to_string(),
                };
                self.prefix = Some(format!("{indent}{marker}"));
            }
            "pre" => {
                self.block(2);
                self.flush();
                self.out.push_str("```");
                self.fence = Some(self.out.len());
                let lang = language(attrs);
                self.out.push_str(&lang);
                self.out.push('\n');
                if !lang.is_empty() {
                    self.fence = None;
                }
                self.pre += 1;
            }
            // Inside a `<pre>` this is the element that names the language,
            // and mdBook puts it there rather than on the `<pre>`.
            "code" if self.pre > 0 => {
                if let Some(at) = self.fence.take() {
                    let lang = language(attrs);
                    self.out.insert_str(at, &lang);
                }
            }
            "code" | "tt" | "kbd" | "samp" => {
                self.flush();
                self.out.push('`');
            }
            "tr" => self.block(1),
            "td" | "th" => {
                if !self.out.is_empty() && !self.out.ends_with('\n') && self.pending == 0 {
                    self.out.push_str(" | ");
                }
            }
            _ => {}
        }
    }

    fn close(&mut self, name: &str) {
        // A marker belongs to the element that set it. An `<h1>` whose only
        // content was a skipped anchor leaves a `# ` behind, and without this
        // the next paragraph on the page wears it.
        if BLOCKS.contains(&name) {
            self.prefix = None;
        }
        match name {
            "p" | "div" | "section" | "blockquote" | "dd" | "dt" | "figcaption" | "summary"
            | "details" | "table" | "caption" | "fieldset" | "address" | "h1" | "h2" | "h3"
            | "h4" | "h5" | "h6" | "tr" => self.block(2),
            "ul" | "ol" | "dl" => {
                self.lists.pop();
                self.block(2);
            }
            "li" => self.block(1),
            "pre" => {
                self.pre = self.pre.saturating_sub(1);
                self.fence = None;
                if !self.out.ends_with('\n') {
                    self.out.push('\n');
                }
                self.out.push_str("```");
                self.block(2);
            }
            "code" | "tt" | "kbd" | "samp" if self.pre == 0 => self.out.push('`'),
            _ => {}
        }
    }

    /// Owe `n` newlines before whatever comes next.
    fn block(&mut self, n: usize) {
        if self.pre > 0 {
            return;
        }
        self.pending = self.pending.max(n);
    }

    /// Pay what is owed, and write the marker that was waiting on it.
    fn flush(&mut self) {
        if self.pending > 0 {
            if !self.out.is_empty() {
                while self.out.ends_with(' ') {
                    self.out.pop();
                }
                for _ in 0..self.pending {
                    self.out.push('\n');
                }
            }
            self.pending = 0;
        }
        if let Some(prefix) = self.prefix.take() {
            self.out.push_str(&prefix);
        }
    }

    fn text(&mut self, raw: &str) {
        let decoded = decode(raw);
        if self.pre > 0 {
            if !decoded.trim().is_empty() {
                self.fence = None;
            }
            self.out.push_str(&decoded);
            return;
        }
        if decoded.trim().is_empty() {
            // Whitespace between tags is still whitespace: `<b>a</b> <i>b</i>`
            // is two words. It is not a reason to pay a pending newline.
            let joinable = !self.out.is_empty()
                && !self.out.ends_with(char::is_whitespace)
                && self.pending == 0
                && self.prefix.is_none()
                && !decoded.is_empty();
            if joinable {
                self.out.push(' ');
            }
            return;
        }
        self.flush();
        if decoded.starts_with(char::is_whitespace)
            && !self.out.is_empty()
            && !self.out.ends_with(char::is_whitespace)
        {
            self.out.push(' ');
        }
        for (i, word) in decoded.split_whitespace().enumerate() {
            if i > 0 {
                self.out.push(' ');
            }
            self.out.push_str(word);
        }
        if decoded.ends_with(char::is_whitespace) {
            self.out.push(' ');
        }
    }

    /// Tidy what the walk produced: markers nothing followed, trailing
    /// spaces, and runs of blank lines.
    fn finish(&mut self) -> String {
        let mut out = String::with_capacity(self.out.len());
        let mut blanks = 0;
        for line in self.out.lines() {
            let line = line.trim_end();
            // A heading or a bullet with no text after it: the element was
            // empty, or held only furniture.
            let empty_marker = !line.is_empty()
                && (line.chars().all(|c| c == '#')
                    || line.trim() == "-"
                    || line.trim() == "``"
                    || bare_number(line));
            if line.is_empty() || empty_marker {
                blanks += 1;
                continue;
            }
            if !out.is_empty() {
                out.push_str(if blanks > 0 { "\n\n" } else { "\n" });
            }
            blanks = 0;
            out.push_str(line);
        }
        out.push('\n');
        out
    }
}

/// `3.` with nothing after it: an `<li>` that held only furniture.
fn bare_number(line: &str) -> bool {
    let digits = line.trim().trim_end_matches('.');
    line.trim().ends_with('.') && !digits.is_empty() && digits.chars().all(|c| c.is_ascii_digit())
}

fn collapse(s: &str) -> String {
    s.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// The entities that turn up in prose, and the numeric forms.
///
/// Not the full table of 2,231 names: the rest are rarer than the mistakes
/// that would come with typing them out, and an entity left undecoded is
/// visible as `&hellip;` rather than wrong in a way nobody would notice.
fn decode(s: &str) -> Cow<'_, str> {
    if !s.contains('&') {
        return Cow::Borrowed(s);
    }
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while let Some(i) = rest.find('&') {
        out.push_str(&rest[..i]);
        let after = &rest[i + 1..];
        let end = after.find(';').filter(|&e| e <= 10);
        match end.and_then(|e| named(&after[..e])) {
            Some(c) => {
                out.push(c);
                rest = &after[end.unwrap() + 1..];
            }
            None => {
                out.push('&');
                rest = after;
            }
        }
    }
    out.push_str(rest);
    Cow::Owned(out)
}

fn named(name: &str) -> Option<char> {
    if let Some(digits) = name.strip_prefix('#') {
        let code = match digits.strip_prefix(['x', 'X']) {
            Some(hex) => u32::from_str_radix(hex, 16).ok()?,
            None => digits.parse().ok()?,
        };
        return char::from_u32(code);
    }
    Some(match name {
        "amp" => '&',
        "lt" => '<',
        "gt" => '>',
        "quot" => '"',
        "apos" => '\'',
        "nbsp" => '\u{a0}',
        "hellip" => '…',
        "mdash" => '—',
        "ndash" => '–',
        "lsquo" => '\u{2018}',
        "rsquo" => '\u{2019}',
        "ldquo" => '\u{201c}',
        "rdquo" => '\u{201d}',
        "times" => '×',
        "middot" => '·',
        "bull" => '•',
        "copy" => '©',
        "reg" => '®',
        "trade" => '™',
        "deg" => '°',
        "laquo" => '«',
        "raquo" => '»',
        "shy" => '\u{ad}',
        "para" => '¶',
        "sect" => '§',
        "dagger" => '†',
        "larr" => '←',
        "rarr" => '→',
        _ => return None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn prose_comes_out_and_furniture_does_not() {
        let page = extract(
            r#"<html><head><title>Ch. 3 &mdash; Guessing</title></head>
               <body>
                 <nav class="sidebar"><a href="/book/ch01.html">Chapter 1</a></nav>
                 <main>
                   <h2>Storing Values</h2>
                   <p>A <code>let</code> statement binds a <em>value</em>.</p>
                   <div id="menu-bar"><button>Theme</button></div>
                   <pre><code class="language-rust,ignore">let x = 5;
let y = x &lt; 6;</code></pre>
                   <ul><li>First</li><li>Second</li></ul>
                   <p>See <a href="ch04.html">ownership</a>.</p>
                 </main>
                 <script>if (a < b) { document.write("</p>nonsense"); }</script>
               </body></html>"#,
        );

        assert_eq!(page.title, "Ch. 3 — Guessing");
        assert_eq!(
            page.text,
            "## Storing Values\n\n\
             A `let` statement binds a value.\n\n\
             ```rust\nlet x = 5;\nlet y = x < 6;\n```\n\n\
             - First\n- Second\n\n\
             See ownership.\n"
        );
        // The sidebar is not in the text, but its links are still links:
        // that sidebar is the book's table of contents.
        assert_eq!(page.links, ["/book/ch01.html", "ch04.html"]);
    }

    /// The shape of every heading mdBook and rustdoc generate: an anchor,
    /// classed `header`, linking the heading to itself. It came out as
    /// nothing at all once, and left its `#` on the paragraph below.
    #[test]
    fn a_heading_that_links_to_itself_is_still_a_heading() {
        let page = extract(
            r##"<main><h2 id="x"><a class="header" href="#x">Ownership</a></h2>
                <p><em>by somebody</em></p></main>"##,
        );
        assert_eq!(page.text, "## Ownership\n\nby somebody\n");
    }

    /// Every one of these has ended a scan in a loop or a panic at some point
    /// while this was being written.
    #[test]
    fn broken_markup_is_text_not_a_crash() {
        assert!(extract("<p>a < b and c > d</p>").text.contains("a < b and c > d"));
        assert!(extract("<p>unclosed").text.contains("unclosed"));
        assert_eq!(extract("<a href=\"x\" title=\"a > b\">hi</a>").links, ["x"]);
        assert_eq!(extract("<!-- never closed <p>hi").text, "\n");
        assert_eq!(extract("").text, "\n");
        assert_eq!(extract("<div><div><div>").text, "\n");
        // A `<nav>` that never closes takes the rest with it, and says so by
        // producing nothing rather than by hanging.
        assert_eq!(extract("<nav><p>menu").text, "\n");
    }

    #[test]
    fn entities_become_the_characters_they_name() {
        assert_eq!(decode("a &amp; b &#65; &#x42; &hellip; &unknown; &"), "a & b A B … &unknown; &");
        assert_eq!(decode("plain"), "plain");
    }

    /// The token rule: a class is a list of words, and a word that merely
    /// contains "search" is not a search box.
    #[test]
    fn furniture_is_matched_by_token_not_by_substring() {
        assert!(furniture(r#" class="sidebar-resize-handle""#));
        assert!(furniture(r#" id="menu-bar""#));
        assert!(furniture(r#" role="navigation""#));
        assert!(!furniture(r#" class="research-notes""#));
        assert!(!furniture(r#" class="content""#));
        assert!(!furniture(""));
    }

    #[test]
    fn attributes_survive_quoting() {
        assert_eq!(attr(r#" href='a b' class="x""#, "href"), Some("a b"));
        assert_eq!(attr(r#" href=plain rel=next"#, "href"), Some("plain"));
        // `data-href` is not `href`, and neither is a bare word.
        assert_eq!(attr(r#" data-href="x""#, "href"), None);
        assert_eq!(attr(r#" href"#, "href"), None);
    }
}
